### PR TITLE
Windows support

### LINKED ISSUE #17: Windows: unknown symbol `__imp_CryptAcquireContextW'
http://sscce.org/ on Windows (Server 2012 R2 - Amazon AMI):

```
> dverify (PublicKey foo) "bar" (Signature "baz")
ghc.EXE: C:\sr\snapshots\a78c6a89\lib\x86_64-windows-ghc-8.0.1\ed25519-0.0.5.0-CpxZaSit3v24CALRG61NQp\HSed25519-0.0.5.0-CpxZaSit3v24CALRG61NQp.o: unknown symbol `__imp_CryptAcquireContextW'
```

cc @thoughtpolice

### PR DESCRIPTION
**Pull request by domenkozar**
Fixes #17 /cc @thoughtpolice 

Note that one can't run tests on Windows atm, but that's a separate issue.

@thoughtpolice if you care to setup appveyor.com account I'll get the windows build going and fix tests.

### CODE REVIEW

**Comment by domenkozar** [comment]
In order to also address #16 I've dropped support for GHC 7.0.1, it's 6 years old.

**Comment by domenkozar** [comment]
@thoughtpolice friendly ping :)

**Comment by thoughtpolice** [comment]
Doh, can't believe I forgot something this simple! I'll cherry pick your patches in shortly, thanks!

**Comment by thoughtpolice** [comment]
@domenkozar I've fixed this and added appveyor support, so we'll see how it goes and what needs to be fixed. Thanks for all this! I've also been meaning to improve the RNG interface on Windows (maybe use `RtlGenRandom`), so this is good insurance to make sure it works..

**Comment by domenkozar** [comment]
Thanks! I'd appreciate a release once you're confident with the changes.

**Comment by domenkozar** [comment]
@thoughtpolice any chance of a release? :)

**Comment by thoughtpolice** [comment]
@domenkozar Sorry about the delay on this... I've still got to write a lot of docs to address some of the points in #12 for end-user confusion and I'd like to do it all at once rather than do two releases. I'll try to sit down and write the prose today...

**Pull request closed without merging**
